### ISSUE TITLE
many problems with installation on windows

### ISSUE THREAD

**Issue by Claudioappassionato** [TheBlewish/Automated-AI-Web-Researcher-Ollama#49]
it's a shame, too many problems with installation on windows. 1: pip install fails on building llama-cpp-python 2 the requirements.txt file has to be redone - After hours it has to give up

**Comment by synth-mania** [comment]
Use WSL

**Comment by leapingturtlefrog** [comment]
> Use WSL

Yes, specifically:
## Running on Windows
To use this application on Windows, you'll need to install **WSL 2** (if you already have it, skip to step 4).

1. Open an administrator terminal and run the following command:
    ```cmd
    wsl --install
    ```
2. Once the installation is complete, press the Windows key and search for "Ubuntu" to launch WSL 2.
3. Follow the on-screen instructions to complete the Ubuntu setup.
4. Proceed from the beginning with the installation and usage steps in the WSL terminal.

Or if you would prefer to not use WSL there is [github.com/hafeezhmha/Automated-AI-Web-Researcher-Ollama](https://github.com/hafeezhmha/Automated-AI-Web-Researcher-Ollama)

**Comment by TheBlewish** [comment]
Hey! 

I've created a new branch called `feature/windows-support` with the Windows compatible version of the program. For anyone having Windows-related issues, you can now find the Windows-friendly version there! 

Just grab that branch instead of main if you're on Windows and it should work better for you. Thanks to @hafeezhmha for the Windows compatibility fixes!

I'll be closing Windows-related issues since there's now a dedicated Windows version available. Feel free to open new issues if you run into any problems with the Windows branch.
