### ISSUE TITLE
Support and continue past research

### ISSUE THREAD

**Issue by amirzamli** [TheBlewish/Automated-AI-Web-Researcher-Ollama#64]
Hi, I want the research to be a living project that can grow and be amended over time. And I would like to handpick a few resources to provide the model which can be difficult to get just by scraping, how can i do that?

My question is essentially two part:
1. How can I continue past research instead of starting over
2. How can i support the research with handpicked content, or helping it download paywalled content.

**Comment by TheBlewish** [comment]
You know what mate, you ask me this while I am a little hammered on whiskey (I spent like 3 months making this program from scratch so I may have earned it idk) I have a final exam tomorrow for my math quiz, but this is an excellent question, due to the math exam tomorrow I may take a day, or four (I have another final exam 2 days after the math one last one for the trimester finally!)  I will try and update this to address your concerns, that is an interesting idea! 
switching the LLM from the research phase to the summary phase, does sound at least intriguing, and I have meant to add an ability to continue past research for a while now so I WILL LOOK INTO IT BROTHER!!!
if I remember anyways if note reopen this!

**Comment by amirzamli** [comment]
Great contribution bro, just dont stress too much about it, take care!

**Comment by flooryyyy** [comment]
was trying to see if anyone else is experiencing issues with summary after research mode ends and saw this. 

treat it as a reminder :D
